name = "image-zip"
compatibility_date = "2024-12-01"

# 配置 Cloudflare Pages
pages_build_output_dir = "./dist"compatibility_flags = ["nodejs_compat"]

# 静态站点配置
[env.production]
account_id = ""  # 您的 Cloudflare 账户 ID
